PUT http://localhost:8000/user/4
Content-Type: application/json

{
    "id": 4,
    "nick": "gblack223",
    "nom":"Geremias",
    "ape":"Johnson",
    "email":"gjohnson@hotmail.com"
}

###
PUT http://localhost:8000/user/4
Content-Type: application/json

{
    "id": 4,
    "nick": "gblack223",
    "nom":"Geremias",
    "ape":"Johnson",
    "email":"gjohnson@gmail.com"
}