POST http://127.0.0.1:8000/prod
Content-Type: application/json
//FORMATO product(id, desc, price{USD}, stock, marca, cat, sCat)
{
    "id": 4,
    "desc": "Sombrero Clasico Negro",
    "price":80,
    "stock":5000,
    "marca":"Universal",
    "cat":"Undefined",
    "sCat":"Cabeza"
    }
