# @name login
//LOGIN COMO ADMIN
POST http://localhost:8000/login 
Content-Type: application/json

{
"nickname":"admin", 
"psw":"1234"
}

### LOGIN COMO CLIENTE
# @name login
POST http://localhost:8000/login 
Content-Type: application/json

{
		"nickname": "lulaluna",
		"psw": "1234"
}

//Req incorrecto para generar unknown endpoint
###
GET http://localhost:8000/u
Authorization: Bearer {{ login.response.body.token }}


// ---------------------------- GETTERS - USUARIOS ---------------------------- //

// ----------- GET DEL USUARIO PROPIO - SOLO USUARIOS LOGEADOS ----------- //
###
GET http://localhost:8000/user/me
Authorization: Bearer {{ login.response.body.token }}


// ----------- GET - SOLO ADMIN ----------- //
###
GET http://localhost:8000/user
Authorization: Bearer {{ login.response.body.token }}

###
GET http://localhost:8000/user/1
Authorization: Bearer {{ login.response.body.token }}

### FILTRO SIMPLE
GET http://localhost:8000/user/permisos/cliente
Authorization: Bearer {{ login.response.body.token }}

### BUSQUEDA CON FILTROS
GET http://localhost:8000/user?nickname=admin&nombre=Emanuel&apellido=Ramirez&email=emaR123@hotmail.com
Authorization: Bearer {{ login.response.body.token }}


// ---------------------------- INSERTS ---------------------------- //
// ---------------------------- INSERTS ---------------------------- //

// ---------------------------- INSERTS ---------------------------- //
// ---------------------------- INSERTS ---------------------------- //

// ---------------------------- INSERTS ---------------------------- //
// ---------------------------- INSERTS ---------------------------- //

// ---------------------------- PERMISOS ---------------------------- // --> Los permisos ya deberian estar subidos en la Base de Datos. No son actualizables.
// ---------------------------- USUARIOS ---------------------------- //
//FORMATO user(id, nick, nom, ape, email)

// EL Insert del Admin tiene que estar hecho previamente para poder
// logearse en el sistema y hacer el resto de inserts.


###
POST http://127.0.0.1:8000/user
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "nickname": "LaLuna",
    "password": "1234",
    "nombre":"Luna",
    "apellido":"Gomez",
    "email":"lluna@gmail.com",
    "permisoCodPermiso":2
}


###
POST http://127.0.0.1:8000/user
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "nickname": "mariaMF",
    "password": "hola1234",
    "nombre":"Maria",
    "apellido":"Fernandez",
    "email":"MF_123@yahoo.com.ar",
    "permisoCodPermiso":2
}


// ---------------------------- CATEGORIAS ---------------------------- //
//FORMATO categoria(id, desc)

### 
POST http://127.0.0.1:8000/cat
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Male"
}

### 
POST http://127.0.0.1:8000/cat
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Female"
}

### 
POST http://127.0.0.1:8000/cat
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Mixto"
}

### 
POST http://127.0.0.1:8000/cat
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Undefined"
}

// ---------------------------- MARCAS ---------------------------- //
//FORMATO marca(id, nombre)

###
POST http://127.0.0.1:8000/marca
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "nombre": "Adidas"
}

###
POST http://127.0.0.1:8000/marca
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "nombre": "Nike"
}

###
POST http://127.0.0.1:8000/marca
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "nombre": "Rebook"
}

###
POST http://127.0.0.1:8000/marca
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "nombre": "Puma"
}

// ---------------------------- SUBCATEGORIAS ---------------------------- //
//FORMATO subcategoria(id, desc)

###
POST http://127.0.0.1:8000/scat
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Torso"
}


###
POST http://127.0.0.1:8000/scat
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Pantalones"
}

###
POST http://127.0.0.1:8000/scat
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Calzado"
}



// ---------------------------- PRODUCTOS ---------------------------- //
//FORMATO product(id, desc, price{USD}, stock, marca, cat, sCat)

// ----------- POST - SOLO ADMIN ----------- //


###
POST http://127.0.0.1:8000/prod 
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Zapatillas Airband Azules",
    "precio": 150,
    "stock": 2300,
    "MarcaCodMarca": 1,
    "categoriumCodCat": 3,
    "subCategoriumCodSCat": 3
}



### 

POST http://127.0.0.1:8000/prod 
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Remera Clasica Tipo A Roja",
    "precio": 50,
    "stock": 10000,
    "MarcaCodMarca":4,
    "categoriumCodCat":1,
    "subCategoriumCodSCat": 1
}
### 
POST http://127.0.0.1:8000/prod 
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Jean Semi Roto Azul",
    "precio": 100,
    "stock": 2000,
    "MarcaCodMarca": 3,
    "categoriumCodCat":2,
    "subCategoriumCodSCat": 2
    }
### 
POST http://127.0.0.1:8000/prod 
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Zapatos Negros Clasicos",
    "precio": 75,
    "stock": 3500,
    "MarcaCodMarca": 1,
    "categoriumCodCat": 1,
    "subCategoriumCodSCat": 3
    }
### 
POST http://127.0.0.1:8000/prod 
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "descripcion": "Tacones Altos Rojos Brillantes",
    "precio": 80,
    "stock": 2950,
    "MarcaCodMarca": 2,
    "categoriumCodCat":2,
    "subCategoriumCodSCat": 3
    }
### 
POST http://127.0.0.1:8000/prod 
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

    {
    "descripcion": "Remera Comun Tipo B Azul",
    "precio": 100,
    "stock": 2000,
    "MarcaCodMarca": 3,
    "categoriumCodCat":3,
    "subCategoriumCodSCat": 1
    }





// ---------------------------- PUT - UPDATE ---------------------------- //
// ---------------------------- PUT - UPDATE ---------------------------- //

// ---------------------------- PUT - UPDATE ---------------------------- //
// ---------------------------- PUT - UPDATE ---------------------------- //

// ---------------------------- PUT - UPDATE ---------------------------- //
// ---------------------------- PUT - UPDATE ---------------------------- //



// ---------------------------- PRODUCTOS ---------------------------- //
//FORMATO product(id, desc, price{USD}, stock, marca, cat, sCat)

// ----------- PUT - SOLO ADMIN ----------- //
###
PUT http://localhost:8000/prod/7
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 7,
    "desc": "Sombrero Clasico Blanco",
    "price":70,
    "stock":5000,
    "marca":"Universal",
    "cat":"Undefined",
    "sCat":"Cabeza"
}

###
PUT http://localhost:8000/prod/7
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 7,
    "desc": "Sombrero Clasico Negro",
    "price":80,
    "stock":5000,
    "marca":"Universal",
    "cat":"Undefined",
    "sCat":"Cabeza"
}

// ---------------------------- CATEGORIAS ---------------------------- //

// ----------- PUT - SOLO ADMIN ----------- //
###
PUT http://localhost:8000/cat/4
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "id":4,    
    "desc":"Indefinido"
}

###
PUT http://localhost:8000/cat/4
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "id":4,    
    "desc":"Undefined"
}


// ---------------------------- SUBCATEGORIAS ---------------------------- //


// ----------- PUT - SOLO ADMIN ----------- //
###
PUT http://localhost:8000/scat/4
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 4,
    "desc": "Head"
}

###
PUT http://localhost:8000/scat/4
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 4,
    "desc": "Cabeza"
}


// ---------------------------- MARCAS ---------------------------- //
// ----------- PUT - SOLO ADMIN ----------- //
###
PUT http://localhost:8000/marca/4
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "id":4,    
    "desc":"Universal Clothes"
}
###
PUT http://localhost:8000/marca/4
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "id":4,    
    "desc":"Universal"
}

// ---------------------------- USUARIOS ---------------------------- //

// ----------- PUT - SOLO ADMIN ----------- //
###
PUT http://localhost:8000/user/4
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 4,
    "nick": "gblack223",
    "nom":"Geremias",
    "ape":"Johnson",
    "email":"gjohnson@hotmail.com"
}

###
PUT http://localhost:8000/user/4
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 4,
    "nick": "gblack223",
    "nom":"Geremias",
    "ape":"Johnson",
    "email":"gjohnson@gmail.com"
}




// ---------------------------- DELETES ---------------------------- //
// ---------------------------- DELETES ---------------------------- //

// ---------------------------- DELETES ---------------------------- //
// ---------------------------- DELETES ---------------------------- //

// ---------------------------- DELETES ---------------------------- //
// ---------------------------- DELETES ---------------------------- //


// ---------------------------- PRODUCTOS ---------------------------- //

// ----------- DELETE - SOLO ADMIN ----------- //
###
DELETE http://localhost:8000/prod/1
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}


// ---------------------------- CATEGORIAS ---------------------------- //

// ----------- DELETE - SOLO ADMIN ----------- //
###
DELETE http://localhost:8000/cat/4
Authorization: Bearer {{ login.response.body.token }}

// ---------------------------- SUBCATEGORIAS ---------------------------- //

// ----------- DELETE - SOLO ADMIN ----------- //
###
DELETE http://localhost:8000/scat/1
Authorization: Bearer {{ login.response.body.token }}

// ---------------------------- MARCAS ---------------------------- //

// ----------- DELETE - SOLO ADMIN ----------- //
###
DELETE http://localhost:8000/marca/4
Authorization: Bearer {{ login.response.body.token }}

// ---------------------------- USUARIOS ---------------------------- //

// ----------- DELETE - SOLO ADMIN ----------- //
###
DELETE http://localhost:8000/user/4
Authorization: Bearer {{ login.response.body.token }}


