# @name login
//LOGIN COMO ADMIN
POST http://localhost:8000/login 
Content-Type: application/json

{
"nickname":"admin", 
"psw":"12345"
}

### LOGIN COMO CLIENTE
POST http://localhost:8000/login 
Content-Type: application/json

{
"nickname":"mariaMF", 
"psw":"hola1234"
}

// ---------------------------- PRODUCTOS ---------------------------- //
//FORMATO product(id, desc, price{USD}, stock, marca, cat, sCat)

// ----------- POST - SOLO ADMIN ----------- //
### 

POST http://127.0.0.1:8000/prod 
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}


{
    "desc": "Sombrero Clasico Negro",
    "price":80,
    "stock":5000,
    "marca":"Universal",
    "cat":"Undefined",
    "sCat":"Cabeza"
    }

// ----------- PUT - SOLO ADMIN ----------- //
###
PUT http://localhost:8000/prod/7
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 7,
    "desc": "Sombrero Clasico Negro",
    "price":70,
    "stock":5000,
    "marca":"Universal",
    "cat":"Undefined",
    "sCat":"Cabeza"
}

###
PUT http://localhost:8000/prod/7
Content-Type: application/json 
Authorization: Bearer {{ login.response.body.token }}

{
    "id": 7,
    "desc": "Sombrero Clasico Negro",
    "price":80,
    "stock":5000,
    "marca":"Universal",
    "cat":"Undefined",
    "sCat":"Cabeza"
}